### ISSUE TITLE
Anglicization of Arabic?

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ArabicInSanskrit#10]
@jlreeder 

Hi, Jason -
  I've been working the italicized text in MW72, with special attention to deciding whether a given
snippet of italicized text represents Sanskrit or some non-Sanskrit language.

The particular case in question here is:
```
<P>.{#ikkavAla#}¦ {%ikkava1la%} in astrology = <Arabic>إِقْبال</Arabic>
<>{%iqba10l,%} good fortune, prosperity.
```
![image](https://cloud.githubusercontent.com/assets/6393033/20233995/c845d67e-a843-11e6-97fd-4e2e5f626cc8.png)

And in particular, that slightly smudged italicized word  (iqbal) that appears after the Arabic script.

When I pasted the Arabic into Goggle Translate, and asked for the word to be pronounced, the word
sounds very much like 'iqbal' !.

So, my suspicion is that this iqbal  is an Anglicization of the Arabic.

Does this sound right?

A minor subsidiary question:  You'll notice that the transliteration shows 'iqba10l', where that '10' generally indicates that the preceding letter ('a' in this case) appears in the print with a circumflex diacritic  : â , which would be (in MW1899 sanskrit) a long 'a'. 
 Due to the print smudge, it's hard to tell if this diacritic is present -  can you  determine whether this
'a' should be a 'long' vowel?

Thanks for the help!

**Comment by drdhaval2785** [comment]
It has to be a10.
It is a common name in India. So I know it has to have long A.
Also I can read Urdu letters a bit. Confirmed to be long A.

**Comment by jsonreeder** [comment]
Confirmed, iqbal is transliteration of the Arabic.
And Dhaval is correct, this is a long a (so a10). The original Arabic has a
long a, so it would be very reasonable for that to be reproduced in the
transliteration, although that smudge does make it difficult to read.

**Comment by gasyoun** [comment]
> And Dhaval is correct, this is a long a

Double proof.

**Comment by funderburkjim** [comment]
Thanks to all for response.  Great to have these expert voices.
