### ISSUE TITLE
Another 2 cases in MW72

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ArabicInSanskrit#12]
Jonathan Migliori finished another batch of Greek from MW72, and in the process noticed another two cases of Arabic script:

```
106254 old <>{%nakta%} see p. 463, col. 3), = <Arabic></Arabic> N. of the fifth
106254 new <>{%nakta%} see p. 463, col. 3), = <Arabic></Arabic> N. of the fifth
```
![image](https://cloud.githubusercontent.com/assets/6393033/23325354/b8875b1e-fac2-11e6-9500-7add1e17db2d.png)

```
126354 old <>pared; Bengāli {%phalasā;%} Hindūstānī <Arabic></Arabic> ac-
126354 new <>pared; Bengāli {%phalasā;%} Hindūstānī <Arabic></Arabic> ac-
```

![image](https://cloud.githubusercontent.com/assets/6393033/23325388/ec3e9788-fac2-11e6-8b86-26a9821b7fb8.png)

@jlreeder   Would you fill in the 'new' lines as needed?

Note: At some later point, we need to replace the '<Arabic>` tag with the `<lang>` tag in this MW72 dictionary, as we did with MW.

**Comment by jsonreeder** [comment]
Here's the Arabic for those two cases!

`106254 new <>{%nakta%} see p. 463, col. 3), = <Arabic>نقل</Arabic> N. of the fifth`
`126354 new <>pared; Bengāli {%phalasā;%} Hindūstānī <Arabic>پهالسا</Arabic> ac-`

**Comment by gasyoun** [comment]
@jsonreeder thanks!

**Comment by funderburkjim** [comment]
@jsonreeder   Jonathan noticed a few more greek that should be Arabic.  Will post these tomorrow for you.

We need to change that `<Arabic>` markup to the new improved `<lang>` markup for mw72.  Maybe 
best to wait till Jonathan is done with all the Greek in mw72, as he'll probably find several Arabic instances.

**Comment by gasyoun** [comment]
> best to wait till Jonathan is done with all the Greek in mw72,

It might not end till 2018 :o)

**Comment by funderburkjim** [comment]
Agree to wait to change to the `<lang>` markup until Jonathan is done.

Will add the cases for initial Arabic translation as they arise. @jsonreeder can introduce the Arabic as his time permits.

**Comment by funderburkjim** [comment]
### 05-03-2017 -- new case 1
```
144249 old <>= <Arabic></Arabic>), N. of a prince.
144249 new <>= <Arabic>شاه</Arabic>), N. of a prince.
```
![image](https://cloud.githubusercontent.com/assets/6393033/25682592/c356bc62-3026-11e7-81aa-a29a71f970d3.png)

**Comment by funderburkjim** [comment]
### 05-03-2017 -- new case 2
```
151662 old <>{%+ sāhi%} = <Arabic></Arabic>) {%= prema-nārāyaṇa%}. {%--Premāmṛita%}
151662 new <>{%+ sāhi%} = <Arabic>شاه</Arabic>) {%= prema-nārāyaṇa%}. {%--Premāmṛita%}
```
![image](https://cloud.githubusercontent.com/assets/6393033/25682789/75455dca-3027-11e7-9f28-6a5bfbdb3f54.png)

**Comment by funderburkjim** [comment]
### 05-03-2017 -- new case 3
```
152899 old <>Kaśmīra (<Arabic></Arabic>). [Page0668-c+ 75]
152899 new <>Kaśmīra (<Arabic>فتح شاه</Arabic>). [Page0668-c+ 75]
```
![image](https://cloud.githubusercontent.com/assets/6393033/25682889/ddb0b71a-3027-11e7-8b41-5ea70bc543a1.png)

**Comment by funderburkjim** [comment]
### 05-03-2017 -- new case 4
```
163109 old <>m. ({%śāha%} = <Arabic></Arabic> ‘the terrible king,’ N. of a king.
163109 new <>m. ({%śāha%} = <Arabic>شاه</Arabic> ‘the terrible king,’ N. of a king.
```
![image](https://cloud.githubusercontent.com/assets/6393033/25682990/436d7016-3028-11e7-9cfb-56e7b5746940.png)

**Comment by funderburkjim** [comment]
### 05-03-2017 -- new case 5
```
163985 old <>({%sāhi%} = Persian <Arabic></Arabic>), N. of a king. {%--Bhū-putra,%}
163985 new <>({%sāhi%} = Persian <Arabic>شاه</Arabic>), N. of a king. {%--Bhū-putra,%}
```
![image](https://cloud.githubusercontent.com/assets/6393033/25683143/d5347e54-3028-11e7-9565-cbafb4d00cca.png)

**Comment by jsonreeder** [comment]
I've added in the Arabic for the comments above. Thanks for adding the screenshots - they make the work easy.

I'm happy to add in language tags when you all feel the time is right. I'll hold off for now.
