### ISSUE TITLE
Another 7 cases of mw72 arabic

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ArabicInSanskrit#13]
These cases noticed by Jonathan Migliori in recent continuation of adding Greek text.

Ready for @jsonreeder to do his magic.

**Comment by funderburkjim** [comment]
### Case 1:
```
; Arabic text case 0817: headword=majamudAra, page=0729-b (167160)
167160 old <P>.{#majamudAra#}¦ {%majamudāra =%} <g></g> {%maj-%}
167160 new <P>.{#majamudAra#}¦ {%majamudāra =%} <Arabic>مجموع دار</Arabic>; {%maj-%}
```

![image](https://user-images.githubusercontent.com/6393033/28808420-d9c30e6a-7649-11e7-9259-1a5c99fae9ae.png)

**Comment by funderburkjim** [comment]
### Case 2:

```
; Arabic text case 0858: headword=malika, page=0751-c (172467)
172467 old <P>.{#malika#}¦ {%malika, as,%} m. (= <g></g>), a king.
172467 new <P>.{#malika#}¦ {%malika, as,%} m. (= <Arabic>ملك</Arabic>), a king.
```

![image](https://user-images.githubusercontent.com/6393033/28808459-20555770-764a-11e7-8556-a08c162b0fa6.png)

**Comment by funderburkjim** [comment]
### Case 3:

```
; Arabic text case 0879: headword=mAmudagajanavI, page=0771-c (177193)
177193 old <><g></g> i. e. Mahmūd of Ghaznī.
177193 new <><Arabic>محمود غزنوي</Arabic> i. e. Mahmūd of Ghaznī.
```

![image](https://user-images.githubusercontent.com/6393033/28808483-5eb67e5e-764a-11e7-921f-4174bac13fbc.png)

**Comment by funderburkjim** [comment]
### Case 4:

```
; Arabic text case 0884: headword=mirAKAna, page=0779-a (178891)
178891 old <>Paṭhān chief ({%khāna = %} <g></g>).
178891 new <>Paṭhān chief ({%khāna = %} <Arabic>خان</Arabic>).
```

![image](https://user-images.githubusercontent.com/6393033/28808512-8da1f982-764a-11e7-8ddf-2788e538ef4b.png)

**Comment by funderburkjim** [comment]
### Case 5:

```
; Arabic text case 0892: headword=mukAbilA, page=0781-a (179322)
179322 old <P>.{#mukAbilA#}¦ {%mukābilā =%} <g></g>
179322 new <P>.{#mukAbilA#}¦ {%mukābilā =%} <Arabic>مقابلة</Arabic>
```

![image](https://user-images.githubusercontent.com/6393033/28808543-d0f099d2-764a-11e7-8b41-2e58f745d960.png)

**Comment by funderburkjim** [comment]
### Case 6:

```
; Arabic text case 0893: headword=mukAriRA, page=0781-a (179323)
179323 old <P>.{#mukAriRA#}¦ {%mukāriṇā =%} <g></g>
179323 new <P>.{#mukAriRA#}¦ {%mukāriṇā =%} <Arabic>مقارنة</Arabic>
```

![image](https://user-images.githubusercontent.com/6393033/28808556-f0249376-764a-11e7-8252-92142ba47c5f.png)

**Comment by funderburkjim** [comment]
### Case 7:

```
; Arabic text case 0898: headword=muTaSila, page=0784-b (180106)
180106 old <>the third Yoga (= <g></g>).
180106 new <>the third Yoga (= <Arabic>مُتّصِل</Arabic>).
```

![image](https://user-images.githubusercontent.com/6393033/28808573-1ef6fd6a-764b-11e7-8e00-6478bc14190f.png)

**Comment by jsonreeder** [comment]
Done!

**Comment by gasyoun** [comment]
> Done!

Hurray!

**Comment by funderburkjim** [comment]
These 7 cases now installed.  Thanks, Jason!

Jonathan zoomed through another batch of Greek, and found another two Arabic cases, prepared below
for you.

**Comment by funderburkjim** [comment]
### Case 8:

```
; Arabic text case 0884: headword=murasidAbAda, page=0785-c (180397)
180397 old <>(<g></g>).
180397 new <>(<Arabic>مرشد آباد</Arabic>).
```

![image](https://user-images.githubusercontent.com/6393033/28894206-17ac6cc2-77a2-11e7-95ee-f4b24f37a685.png)

**Comment by funderburkjim** [comment]
### Case 9:

```
; Arabic text case 0887: headword=muSallaha, page=0786-b (180536)
180536 old <>logical term (<g></g>).
180536 new <>logical term (<Arabic>مصالحة</Arabic>).
```

![image](https://user-images.githubusercontent.com/6393033/28894278-4eb94ee2-77a2-11e7-8145-24a4bc1f241f.png)

**Comment by jsonreeder** [comment]
Done!

**Comment by gasyoun** [comment]
@jsonreeder thank you so much.

**Comment by funderburkjim** [comment]
Thanks, Jason.  Hope all is well with you in Google-land.

**Comment by jsonreeder** [comment]
Thanks @funderburkjim! Actually left Google-linguistics-land and started working at a startup doing web development. I miss Arabic a bit, but it's super exciting to have my nose in code all day.

**Comment by gasyoun** [comment]
> left Google-linguistics-land and started working at a startup

Oh, great to have you still around.
