### ISSUE TITLE
additional case arabic in mw72

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ArabicInSanskrit#14]
Several months ago, @jmigliori  finished providing Greek text in MW72 (see https://github.com/sanskrit-lexicon/GreekInSanskrit/issues/31), and noticed an additional case of Arabic script.  I just installed the Greek changes today, hence this note.

```
343008 old <div n="lb"/>Sanskrit word, cf. <lang n="arabic"></lang>), permission to go away,
343008 new <div n="lb"/>Sanskrit word, cf. <lang n="arabic"></lang>), permission to go away,
```

![image](https://user-images.githubusercontent.com/6393033/67817472-e4ee6800-fa83-11e9-9030-099c79793fde.png)

Maybe @jsonreeder is still seeing notes from this repository and can provide the Arabic script.

**Comment by jsonreeder** [comment]
Though that word means "farewell," I'm happy to see this greeting. :-)

Here's the Arabic:

```
343008 old <div n="lb"/>Sanskrit word, cf. <lang n="arabic"></lang>), permission to go away,
343008 new <div n="lb"/>Sanskrit word, cf. <lang n="arabic">وداع</lang>), permission to go away,
```

**Comment by funderburkjim** [comment]
Hi, @jsonreeder ,   Thank you for the prompt reply.  The change is now installed.

Incidentally, are you working now with Peter at sanskritlibrary.org?

**Comment by jsonreeder** [comment]
Yes, I am!

**Comment by funderburkjim** [comment]
Since Peter has an ongoing interest in the dictionary work at Cologne, it might be good for you to be
aware of the changes in approach we are currently undergoing.   In particular,  we are aiming to
greatly streamline the process of making local installations  of the dictionaries.  Also, you might come up with some good suggestions regarding documentation or perhaps procedures.  Does this sound like something you would want to investigate further?

**Comment by funderburkjim** [comment]
@jsonreeder  Did you see note above?

**Comment by gasyoun** [comment]
> Also, you might come up with some good suggestions regarding documentation or perhaps procedures.

Guess he did not yet.
