### ISSUE TITLE
MW arabic words, part 3

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ArabicInSanskrit#3]
In September, 2014, @gasyoun provided Arabic text for some MW headwords.  For the sake of having all the occasions of Arabic text in MW in one place, I am showing these cases in this issue.

**Comment by funderburkjim** [comment]
1 araGawwa
a wheel or machine for raising water from a well (Hind. ارهٿ) Pañcat. 

```
<H3><h><hc3>110</hc3><key1>araGawwa</key1><hc1>3</hc1><key2>ara--Gawwa</key2></h>
<body> <lex>m.</lex> <c>a_wheel_or_machine_for_raising_water_from_a_well_<p><ab>Hind.
</ab>_ ارهٿ</p></c> <ls>Pan5cat.</ls> </body><tail><pc>86,2</pc> <L>15014</L></tail></H3>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5810899/cc79c80e-a01b-11e4-80f5-a965bb59e343.png)

**Comment by funderburkjim** [comment]
2 hEdaraSAha
m. = حيدرشاۀ Cat. 

```
<H1><h><hc3>110</hc3><key1>hEdaraSAha</key1><hc1>1</hc1><key2>hEdaraSAha</key2></h>
<body> <lex>m.</lex> <c>=_ حيدرشاۀ</c> <ls>Cat.</ls> </body><tail><mul/> <MW>166068</MW> 
<pc>1305,3</pc> <L>264434</L></tail></H1>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5810952/967054fc-a01c-11e4-89a2-53221c70c34c.png)

**Comment by funderburkjim** [comment]
3 huRqikA
f. (Pers. هندي) a bill of exchange, bond Rājat. 

```
<H1><h><hc3>110</hc3><key1>huRqikA</key1><hc1>1</hc1><key2>huRqikA</key2></h><body> 
<lex>f.</lex> <p><ab>Pers.</ab>_ هندي</p> <c>_a_bill_of_exchange_,_bond</c> <ls>Ra1jat.</ls> 
</body><tail><pc>1301,2</pc> <L>263542</L></tail></H1>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5810964/db3c06c6-a01c-11e4-8e36-9df154756ea5.png)

**Comment by funderburkjim** [comment]
4 hindu
m. (fr. the Persian هندو) a Hindu (more properly Hindu1) .
_Hindu1 was recoded, as shown below (ejf)_

```
<H1><h><hc3>110</hc3><key1>hindu</key1><hc1>1</hc1><key2>hindu</key2></h><body> 
<lex>m.</lex> <p>fr._the_Persian_ هندو</p>_a_Hindu_<p>more_properly_<as0>Hindu1</as0><as1>
<s>hindU</s></as1></p> <c>.</c> </body><tail><MW>165034</MW> <pc>1298,3</pc> 
<L>262938</L></tail></H1>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5810996/681a7154-a01d-11e4-8cee-6096bd7f83c6.png)

**Comment by funderburkjim** [comment]
5 hikmatprakASa
m. (fr. حكمت) N. of a med. wk. translated from the Arabic by mahA-deva paRqita.

```
<H1><h><hc3>110</hc3><key1>hikmatprakASa</key1><hc1>1</hc1><key2>hikmat-
prakASa</key2></h><body> <lex>m.</lex> <p>fr._ حكمت</p> <c>_N._of_a_med._<ab>wk.
</ab>_translated_from_the_Arabic_by_<as0>Maha1-deva</as0><as1><s>mahA-deva</s>
</as1>_<as0>Pan2d2ita</as0><as1><s>paRqita</s></as1>.</c> </body><tail><mul/> 
<MW>164932</MW> <pc>1298,1</pc> <L>262798</L></tail></H1>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5811010/9796b26c-a01d-11e4-85ab-6f27477d2f36.png)

**Comment by funderburkjim** [comment]
6 sParaka
m. a shield L.  (accord. to some fr. Persian سِپَرْ) .

```
<H2><h><hc3>110</hc3><key1>sParaka</key1><hc1>3</hc1><key2>sParaka</key2></h><body>
<OR group="256787,sPara;256788,sParaka"/> <lex>m.</lex> <c>a_shield</c> <ls>L.</ls> <p>
<ab>accord.</ab>~<c>to_some_fr._Persian_ سِپَرْ</c></p> <c>.</c> </body><tail>
<pc>Page1269,3</pc> <mul/> <MW>160952</MW> <L>256788</L></tail></H2>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5811029/ecaf4e30-a01d-11e4-91fc-85dd84bfc4b8.png)

**Comment by funderburkjim** [comment]
7 sekanDara
m. = اسكندر, Iskandar (Alexander) Cat. 

```
<H1><h><hc3>110</hc3><key1>sekanDara</key1><hc1>1</hc1><key2>sekanDara</key2></h>
<body> <lex>m.</lex> <c>=_ اسكندر_,_Iskandar_<p>Alexander</p></c> <ls>Cat.</ls> </body><tail>
<MW>157825</MW> <pc>1246,1</pc> <L>252079</L></tail></H1>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5811038/23e0e206-a01e-11e4-819f-6928be4beb12.png)

**Comment by funderburkjim** [comment]
8 sAha
m. = شاه (» pradIpa- and maDukara-s°).

```
<H1><h><hc3>110</hc3><key1>sAha</key1><hc1>1</hc1><key2>sAha</key2><hom>2</hom></h>
<body> <lex>m.</lex> <c>=_شاه </c>  <p><see/>~<s>pradIpa-</s>~<c>and</c>~<s>maDukara-
s<sr1/></s></p>. </body><tail><mul/> <MW>153056</MW> <pc>1212,1</pc> <L>243585</L></tail>
</H1>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5811066/7531619e-a01e-11e4-8d4f-782c3e0b1d25.png)

**Comment by funderburkjim** [comment]
9 sahama
n. (fr. Arabic سهم ) good or evil luck arising from the influence of the stars.

```
<H1><h><hc3>110</hc3><key1>sahama</key1><hc1>1</hc1><key2>sahama</key2></h><body> 
<lex>n.</lex> <p>fr._Arabic_ سهم </p> 
<c>_good_or_evil_luck_arising_from_the_influence_of_the_stars.</c> </body><tail>
<MW>150971</MW> <pc>1195,2</pc> <L>240494</L></tail></H1>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5811079/a29f756c-a01e-11e4-9628-03e9ff0f1aa5.png)

**Comment by funderburkjim** [comment]
10 SilamAnaKAna
m. = سليمان خان Cat. 

```
<H1><h><hc3>110</hc3><key1>SilamAnaKAna</key1><hc1>1</hc1><key2>SilamAna-KAna</key2>
</h><body> <lex>m.</lex> <c>=_ سليمان خان </c> <ls>Cat.</ls> </body><tail><mul/> 
<MW>136651</MW> <pc>1073,1</pc> <L>217271</L></tail></H1>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5811091/d54d4ca0-a01e-11e4-882e-f2ccaf3442d8.png)

**Comment by funderburkjim** [comment]
11 SAhnAma
= شاه نامه , Cat. 

```
<H1><h><hc3>000</hc3><key1>SAhnAma</key1><hc1>1</hc1><key2>SAhnAma</key2></h>
<body> <c>=_ شاه نامه </c> , <ls>Cat.</ls> </body><tail><mul/> <MW>136163</MW> <pc>1069,3</pc> 
<L>216480</L></tail></H1>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5811102/0f183e04-a01f-11e4-9b46-5137c8fee317.png)

**Comment by funderburkjim** [comment]
12 SAheva
m. (prob.) = صاحب , Rājat. 

```
<H1><h><hc3>110</hc3><key1>SAheva</key1><hc1>1</hc1><key2>SAheva</key2></h><body> 
<lex>m.</lex> <p>prob.</p> <c>_=_ صاحب </c> , <ls>Ra1jat.</ls> </body><tail><mul/> 
<MW>136162</MW> <pc>1069,3</pc> <L>216479</L></tail></H1>
```

![image](https://cloud.githubusercontent.com/assets/6393033/5811116/46986458-a01f-11e4-8a41-1c129ed6173f.png)

**Comment by funderburkjim** [comment]
This completes the list.
@jlreeder Would you doublecheck these?

**Comment by jsonreeder** [comment]
@funderburkjim No objections.
@gasyoun Nice work.

**Comment by gasyoun** [comment]
@jlreeder there is more, thanks.

**Comment by gasyoun** [comment]
One more 
![7-1183](https://cloud.githubusercontent.com/assets/80761/5857381/581a3d7a-a25c-11e4-91ad-0df00bb9d823.png)
falsely marked as Russian

```
<H1><h><key1>sekaMDara</key1><key2>sekaMDara</key2></h><body><gram n="m">m.</gram> N. pr. = <lang n="Russian">اسكندر</lang> <ls>Verz. d. Oxf. H. 166, N.</ls> <s>°purI</s> <ls>166, 5. 6.</ls></body><tail><L>112553</L><pc>7-1183</pc></tail></H1>
```

@funderburkjim I have added the Arabic, though made no changes to the "Russian" label

**Comment by funderburkjim** [comment]
Problem with sekaMDara occurs in PWG.  I have corrected to mark this as Arabic.

**Comment by gasyoun** [comment]
@funderburkjim close?

**Comment by funderburkjim** [comment]
@jlreeder  @gasyoun   Seems ok to close
