### ISSUE TITLE
Arabic in Wilson Dictionary

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ArabicInSanskrit#6]
@jlreeder 

I've found only 3  cases in the Wilson dictionary where there is Arabic text.
Each of these cases is represented by a comment in this issue.

The comment for a particular case has the format:
- the first line identifies the case number (1 to 3),
- the second line identifies the headword (with a link to the Basic Display for WIL at this headword)
- the third line identifies the page number in question (with a link to the scanned image)
- the fourth line identifies the line number in the digitization wil.txt where the arabic text occurs.

The remaining lines show a sample of the digitization 
- preceding the occurrence of the Arabic text,
- containing the Arabic text, shown as &lt;A&gt;&lt;/A&gt;  (1 case) or &lt;ar&gt;&lt;/ar&gt;  (2 cases)
- following the Arabic text.

It is intended that Jason edit the comment and put the arabic text within the tag line.

These records were generated by programs that made use of the GitHub API.

**Comment by funderburkjim** [comment]
case = 1 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=aYjIra'>aYjIra</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/servepdf.php?page=014'>14</a> 
linenum = 2590

```
derived from this implies the Guava; the term has, possibly, been borrow
ed from

the Persian 
<A>انجير</A>
***NONE***

.E. {#aYja#} to make clear, and {#Iran#} aff.
```

**Comment by funderburkjim** [comment]
case = 2 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=tarambuja'>tarambuja</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/servepdf.php?page=368'>368</a> 
linenum = 72648

```
.{#tarambuja#}¦ n. ({#-jaM#}) A watermelon, (most probably borrowed from
 the

{%Persian,%} 
***NONE***
<ar>تربز</ar>  [JASON:  just replace this, if Arabic text is present]
)

.{#tarapaRya#}¦ n. ({#-RyaM#}) Fare, freight.
```

**Comment by funderburkjim** [comment]
case = 3 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=peroja'>peroja</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/servepdf.php?page=553'>553</a> 
linenum = 108833

```
.E. {#pA#} to drink, Un'a4di aff. {#ru.#}

.{#peroja#}¦ n. ({#-jaM#}) The turquoise: it is the {%Persian%} word 
***NONE***
<ar>فيروزه</ar>

.{#pela#}¦ ({#f#}) {#peRf#} r. 1st cl. ({#pelati#}) To go or move.
```

**Comment by gasyoun** [comment]
@funderburkjim 
Not Arabic, but Persian using Arabic script, if we can trust the text. Jim, if we put such hard work in making the etymologies better, maybe it's time to update the language tags as well?
To call Persian - Arabic and Old Slavic - Russian is not linguistically correct and there is no need to continue with it. There must be a few more of such kind. It's time, Jim, it's time.

**Comment by jsonreeder** [comment]
@funderburkjim All Arabic text entered. Note that I have not removed the note in case 2.

@gasyoun On the Arabic front it's not strictly inaccurate to have all of the text I've transcribed as <ar> because, though most of it is indeed Persian or [old] Turkish, it's all written in Arabic text. As a language tag it's inaccurate. As an alphabet marker it's fine.

**Comment by gasyoun** [comment]
@jlreeder let's make it a language tag?

**Comment by funderburkjim** [comment]
@jlreeder Found one more Arabic alphabet case, incorrectly marked with  &lt;R&gt;.

case = 4 
headword= <a target='_word' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/indexcaller.php?input=slp1&output=deva&key=mahallaka'>mahallaka</a> 
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/WILScan/2014/web/webtc/servepdf.php?page=648'>648</a> 
linenum = 127524

```
{#mahallaka#}¦ m. ({#-kaH#}) An eunuch employed in a {%Ha4ram.%}
.E. {#mahalla#} said to mean the inner apartments, probably the Arabic word
<R>محل</R>  [Note to Jason I'll change the tag to <A> ... Jim]
and {#kan#} added; otherwise with {#Wak#} added {#mahallika#} m.
({#-kaH.#})

```

**Comment by jsonreeder** [comment]
@funderburkjim I've input the Arabic for Case 4. I'm happy to help make these tags language tags, as @gasyoun suggests, but will defer to your judgment and directions.

**Comment by funderburkjim** [comment]
The Arabic for Wilson (4 cases) has been installed.

Regarding `make these tags language tags` --  I found interesting the observation that 'A' (similarly) 'R' are currently
functioning as _alphabet_ tags, rather than _language_ tags.

I cannot provide an informed opinion as to whether partitioning the 'A' alphabetic  into, say 'A' and 'P'  (Arabic language, Persian language) is desireable.   @jlreeder and @gasyoun  should discuss this further in another issue, if they think the tags should be language tags.  I would like to see a clear statement of the reasons why language tags are preferable to alphabet 'A' tag in Wilson and the other dictionaries Jason has worked on.   

The work of this issue is over, I think.
