### ISSUE TITLE
MW72 arabic, another case

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/ArabicInSanskrit#8]
@jlreeder  
Jonathan found another likely Arabic alphabet text in MW72 (see [case 44](https://github.com/sanskrit-lexicon/GreekInSanskrit/issues/14).  This was incorrectly marked as Greek.
I've changed the tag to `<Arabic>`.  Here's the case:
page = <a target='_page' href='http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW72&&page=0080'>0080</a> 
case = 44, hw = ara, page=0080-a

```
18815 new <>water from a well (Hind. <Arabic>أرهٿ</Arabic>); a deep well.

```

If this is Arabic text, would you input it?

Thanks, Jason.

**Comment by jsonreeder** [comment]
@funderburkjim I have added in the Arabic! Nice catch, @jmigliori

**Comment by funderburkjim** [comment]
@jlreeder   Thanks Jason,  This is installed now.

Wish there were more Arabic for you to work on!

**Comment by jsonreeder** [comment]
I’m standing by if they arise, or for the next project!

**Comment by gasyoun** [comment]
@funderburkjim listing through the books is a bad idea? Too timetaking?

**Comment by funderburkjim** [comment]
@jlreeder  found another one!

```
;<H1>100{dArvawa}1{*dArvawa}¦ •n. 
<Arabic></Arabic>
{%Berathungssaal.%} PW49865
```

Here's the scan:
![image](https://cloud.githubusercontent.com/assets/6393033/12382720/24b5fc3c-bd6b-11e5-87e9-bc8fd3a2e962.png)

**Comment by funderburkjim** [comment]
@jlreeder   Oops! Ignore prior message.  I see you have done this under #7,  apparently I omitted installing it.

**Comment by gasyoun** [comment]
@funderburkjim indeed.
